name: AMD Driver Link Updater

on:
  schedule:
    - cron: '0 2 * * 0'  # Run once a week at 2:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-amd-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create directory structure
        run: mkdir -p drivers/amd
        
      - name: Download config JSON
        run: |
          curl -s https://raw.githubusercontent.com/nunodxxd/AMD-Software-Adrenalin/refs/heads/main/configs/config.json -o config.json
      
      - name: Extract and update link
        run: |
          # Extract stable URL from JSON
          NEW_LINK=$(cat config.json | jq -r '.driver_links.stable')
          
          echo "New link: $NEW_LINK"
          
          # Check if value was extracted properly
          if [ -z "$NEW_LINK" ]; then
            echo "Error: Failed to extract new link from JSON"
            exit 1
          fi
          
          # Always update the link.txt file
          echo "$NEW_LINK" > drivers/amd/link.txt
          
          # Debug: show the file we just created
          echo "Content of the updated file:"
          cat drivers/amd/link.txt
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add drivers/amd/link.txt
          git commit -m "Update AMD driver link" || echo "No changes to commit"
          git push origin || echo "No changes to push"